export enum RESPONSE_MESSAGES {
  BOOKING_NOT_FOUND = 'ERR_BOOKING_NOT_FOUND',
  VEHICLE_NOT_FOUND = 'ERR_VEHICLE_NOT_FOUND',
  VEHICLE_INACTIVE = 'ERR_VEHICLE_INACTIVE',
  INVALID_BOOKING_RANGE = 'ERR_INVALID_BOOKING_RANGE',
  BOOKING_OVERLAP = 'ERR_BOOKING_OVERLAP',
  DUPLICATE_DATA = 'ERR_DUPLICATE_DATA',
  DB_FAILURE = 'ERR_DB_FAILURE',
  FIELD_MISSING = 'ERR_REQUIRED_FIELD_MISSING',
  RECORD_NOT_FOUND = 'ERR_RECORD_NOT_FOUND',
}
